### ISSUE TITLE
[wip] Add a basic image server

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/server#14]
Just for case if performance does not matter and a easy environemt (without loris, ...) is needed

**Comment by kerim1** [comment]
At the IISH we are using Loris now, so we do not need a build in basic server. I also have not ported that controller to koa yet. I removed 'sharp' from the packages as well, as it is quite a large dependency for something we'll probably only use in a simple development environment. So, we have to think about how to solve this.

**Comment by Sozialarchiv** [comment]
I would like to let sharp in. It is good if you want to test it something fast. In addition we should support different image servers. So it's good to have another to test.

**Comment by kerim1** [comment]
I was thinking of moving the sharp dependency to devDependencies in package.json so we could ignore it in production mode: https://docs.npmjs.com/files/package.json#devdependencies

**Comment by Sozialarchiv** [comment]
Nice solution.
