### ISSUE TITLE
Loris just accepts id with extensions

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/server#18]
It seems that Loris just accepts id with an extension:

Working:
http://www.example.org/image-service/abcd1234**.jpg**/full/full/0/default.jpg

Not working: 
http://www.example.org/image-service/abcd1234.jpg/full/full/0/default.jpg

# Solution

Here a possible solution:

https://github.com/archival-IIIF/server/blob/master/config/config_example.yaml:
imageServer: 
  url: "http://localhost:8080/loris/"
  addExtensionToId: true

Depending on the config settings we can build the url:
https://github.com/archival-IIIF/server/blob/master/controllers/externalImageServerController.js#L10

@kerim1 Are you planning to use loris?

**Comment by kerim1** [comment]
We are planning to look at various existing IIIF image servers and one or multiple own implementations (sharp etc...) based on some criteria like:
- ease of configuration / maintainability
- support for our requirements
- performance / efficiency
- image format support

Also we will compare various image formats that could be provided as a source format for the image server. Which will probably come down to JPEG vs JPEG-2000 vs TIFF.

Once we have the results from our tests, we will make a decision on which image server to choose.

**Comment by Sozialarchiv** [comment]
If it just about performance and jpeg-2000 I would think about to integrate kakadu in archival-IIIF.

**Comment by kerim1** [comment]
We have made a decision now and are going to use Loris. We'll send the full path to the image to Loris as an identifier, so no need to hide the extension in our use cases.
