### ISSUE TITLE
Support IIIF v3

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/server#25]

**Comment by kerim1** [comment]
Now that v3 has the official beta status and is intended for implementation (and is encouraged by the IIIF consortium to do so), we should consider supporting v3 in the viewer. The server application already provides support for v3 for the digitalized content. How much work would it be for the viewer application to support v3?

**Comment by Sozialarchiv** [comment]
The viewer is using manifesto.js like universalviewer and the upcomming mirador. 

I think manifesto.js can handle v3, but has some issues. I will test it.

**Comment by kerim1** [comment]
Did you already do some tests? 

I added initial support for V3 for the digital born material by adding ?v3 to the manifest or collection URL. So, for example https://iiif.socialhistory.org/iiif/presentation/collection/test for V2 and https://iiif.socialhistory.org/iiif/presentation/collection/test?v3 for V3. Could you see if that works with the viewer?

We are now running IIIF v3 in beta for digitized material and when we will be focussing on digital born material, I would like to move to V3 as well.

**Comment by Sozialarchiv** [comment]
Sounds really good. Thanks a lot. I will do test as soon as I can find the time.

**Comment by kerim1** [comment]
Accidentally closed this!

**Comment by kerim1** [comment]
Now that V3 is stable, I have made the V3 version of the digital born collections/manifest the default and I removed the V2 versions.

**Comment by Sozialarchiv** [comment]
great news
