### ISSUE TITLE
Give a possiblity to detect the language of a manifest file

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/server#28]
@kerim1 @eericq 

I made the viewer multilingual. The support of different languages leads to the question: Which language is the default language in the viewer.

To prevent a language mix I think the viewer should use the same language like the displayed manifest file.

At the it is not possible to determine a language of the manifest:

```
{
  @id: "http://example.com/..."
  @type: "sc:Manifest",
  label: "F113.mpg",
  @context: "http://iiif.io/api/presentation/2/context.json",
  metadata: [
    {
       label: "Published",
       value: "1975"
    }
}
```

I see three solutions

1. We use a content-language in the response header of the manifest
1. We add a language field in the manifests files like in the draft of version 3 https://iiif.io/api/presentation/3.0/#language. A problem here is that this element is not allowed for manifests and collection: https://iiif.io/api/presentation/3.0/#appendices
1. We can use even for single language manifest property values https://iiif.io/api/presentation/2.1/#language-of-property-values. The problem here is, that v2 does not provide the possiblity to translate labels, just values.

In addition we need a way to set the language in server.

For the moment (IIIF 2.x) I would suggest an easy solution:

1. Add a language value in the env file
1. Return it as content-language in the response header of the manifest

**Comment by Sozialarchiv** [comment]
What do you think if the server write the label always with a language: 

`{"@value": "my label", "@language": "en"},`

**Comment by Sozialarchiv** [comment]
@kerim1 What do you think about the suggestion? We definitely need a way to pass the language from the manifest to the viewer.

**Comment by kerim1** [comment]
> What do you think if the server writes the label always with a language:
> 
> `label: {"@value": "my label", "@language": "en"},`

You cannot assume that there will always be a language defined, as it is perfectly valid for a IIIF manifest to have no language defined explicitly.

> @kerim1 What do you think about the suggestion? We definitely need a way to pass the language from the manifest to the viewer.

In most cases, I don't know the language either. So, i'd rather keep it the way it is now.
