### ISSUE TITLE
IIIF manifest builder lib

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/server#30]
Would it be a big work for you to create a standalone IIIF manifest builder lib, that is installable by npm/yarn?

Just the code from here:
https://github.com/archival-IIIF/server/tree/master/src/presentation/elem

It would be very nice if could use your code also in the test-server and the demo respositories. It would make the v3 testing much easier.

**Comment by kerim1** [comment]
I discussed it with Eric and I will look into it soon. Though be aware that only part of the specification is now supported; just whatever was necessary for the server software. Also the v3 still uses one of the older specification drafts (that worked in the UniversalViewer), so not the v3 that is currently in beta.

**Comment by Sozialarchiv** [comment]
Thank you very much.

**Comment by kerim1** [comment]
I moved all the code under `/presentation/elem` to a new repository: https://github.com/archival-IIIF/presentation-builder 
As the code is not complete and the v3 code does not match the current beta draft I decided not to make it installable by npm/yarn. Instead it was a lot easier for now to use git submodules, so I added a submodule to my project: https://github.com/archival-IIIF/server/tree/master/src/presentation
So I would advice to do to the same.

**Comment by Sozialarchiv** [comment]
Thank you very much.

I think the git submodules is a good idea.
