### ISSUE TITLE
Droped support for mediaSequences

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/server#32]
The presenter-builder and the aiiif server is not using mediaSequences for iiif v3. 

mediaSequences is an extension, that is not part of the iiif api. See http://wellcomelibrary.org/ixif/0/context.json

Until now the aiiif viewer took the information from this attribute to render pdf and plain text:

https://iiif.sozialarchiv.ch/?manifest=https://iiif.sozialarchiv.ch/iiif/manifest/Info%2B%2BTest.pdf

I adopted this behavior from the universal viewer. The universal viewer (v2 and v3) only shows a pdf if it is defined in the mediaSequences.

@kerim1 How does the server now provides pdf, txt and any other none audio visual files? With the `rendering` attribute?  Can you post an example?

If the rendering attribute is used I can modify the aiiif viewer that it can extract the information from this attribute. What I think would be a good solution.

But this would not solve the issue for the universal viewer: Without mediaSequences it wont be able to handle manifest files from the aiiif server, which are containing none audio visual files (e.g. PDF). For our use case this is not a big issues. 

@kerim1, @eericq  But what do you think about that?

**Comment by kerim1** [comment]
At the IISH we are already using IIIF v3 for our digitized material in production with the Universal Viewer. The Universal Viewer no longer needs the mediaSequences extension as audio/video, but also other formats, can now be referenced without the extension. The Universal Viewer already supports this.

See this section in the api spec: https://iiif.io/api/presentation/3.0/#57-content-resources The `rendering` is not suitable, as it refers to an alternative resource. We just refer to the PDF in the `body` of the `Annotation` on the `Canvas`. Important is the `type` and `format` to determine what kind of material it is. See also the types in this table: https://iiif.io/api/presentation/3.0/#type  

So for PDF we use the following manifest description: https://access.iisg.amsterdam/iiif/presentation/N30051003097927/manifest?pretty 
```
{
          "id": "https://access.iisg.amsterdam/iiif/presentation/N30051003097927/annopage/1/0",
          "type": "AnnotationPage",
          "items": [
            {
              "id": "https://access.iisg.amsterdam/iiif/presentation/N30051003097927/annotation/15ABE5CD-766F-4385-965F-15B51FEA70E8",
              "type": "Annotation",
              "motivation": "painting",
              "body": {
                "id": "https://access.iisg.amsterdam/file/15ABE5CD-766F-4385-965F-15B51FEA70E8",
                "type": "Text",
                "format": "application/pdf"
              },
              "target": "https://access.iisg.amsterdam/iiif/presentation/N30051003097927/canvas/1"
            }
          ]
        }
```
And the Universal Viewer has no problem rendering this.

**Comment by Sozialarchiv** [comment]
That sounds great.

**Comment by Sozialarchiv** [comment]
I could make it working on the test-server with uv.
