### ISSUE TITLE
IIIF_SERVER_IMAGE_SERVER_NAME missing in .env.example

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/server#34]
https://github.com/archival-IIIF/server/blob/master/.env.example

By the way: Why this value is mandatory can I not use any iiif server?

https://github.com/archival-IIIF/server/blob/master/src/lib/Config.ts#L73

**Comment by kerim1** [comment]
Yes, fixed. You can use any other image server, but it needs to know the profile: https://github.com/archival-IIIF/server/blob/master/src/image/profiles.ts Could be extended later by accepting a path a json file which contains the profile.
