### ISSUE TITLE
Context type errors

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/server#35]
I get several type problems like that:

```
src/image/router.ts:32:20 - error TS2345: Argument of type 'ParameterizedContext<any, RouterParamContext<any, {}>>' is not assignable to parameter o
f type 'Context'.
```

```
src/image/router.ts:49:24 - error TS2345: Argument of type 'ParameterizedContext<any, RouterParamContext<any, {}>>' is not assignable to parameter o
f type 'Context'.
```

**Comment by Sozialarchiv** [comment]
Changing import {Context} from 'koa'; to import {RouterContext} from "@koa/router"; solves the problem for me. Should I make a PR?

**Comment by kerim1** [comment]
I don't have any problems at all; neither does the docker build. How do you compile?

**Comment by Sozialarchiv** [comment]
I dont now why but now  tsc is compiling with Context. 

But Webstrom is still showing errors. 

![grafik](https://user-images.githubusercontent.com/17063042/90632247-6803c900-e224-11ea-8954-9acd5f1109b1.png)

So I think RouterContext is maybe still the better solution:

![grafik](https://user-images.githubusercontent.com/17063042/90632374-95507700-e224-11ea-88a1-db918d834a3b.png)

See also: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36161:
> koa-router call the handler function with RouterContext type , but the handler function we defined need the Context type. Context type maybe defined some other properties which are not in RouterContext, so the type checking can not success.
