### ISSUE TITLE
Rule based authentification system

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/server#8]
Authentifiaction ways:

 * [x] Token (with IIIF Authentifiaction API)
 * [ ] Username and password (with IIIF Authentifiaction API)
 * [x] IP

See also #9

**Comment by Sozialarchiv** [comment]
@kerim1
> For now, the IISH only requires a token based authentication implementation. What will be the requirement for you?

At the moment just IP.

**Comment by kerim1** [comment]
Ok, so username/password will be out-of-scope for now.
